### ISSUE TITLE
bug: Blank page and Incorrect CSS layout

### ISSUE THREAD

**Issue by HueLiu** [tiddly-gittly/TiddlyGit-Desktop#56]
## Environment

Version v0.4.0.

Electron Version: 12.0.6
Node Version: 14.16.0
Chromium Version: 89.0.4389.128

OS (macOS, Windows, Linux) and Version: Windows 10 21H1 x64 Pro

## Description:

1. The GitHub login interface is blank by default when it opens. 
2. It seems to be a CSS issue with the default template.

## Steps to Reproduce:

Screenshots should tell you what's going on :)

## Additional Context
![image](https://user-images.githubusercontent.com/19755727/120890980-a4c87180-c638-11eb-8b0e-42cf1569b95e.png)

![image](https://user-images.githubusercontent.com/19755727/120890935-6af76b00-c638-11eb-9167-3008e164ca46.png)

**Comment by linonetwo** [comment]
For 1, I think add workspace page is working fine? The Github login might be blank, but it will soon jump back to the add workspace page right?

For 2, yes, it crushes into the tags bar.

**Comment by HueLiu** [comment]
Well, I can login to GitHub normally, but after I do, the page goes blank and I can't select the repository I want.

**Comment by linonetwo** [comment]
OH, this normally means something errors, can you right click and open devtool to screenshot the error message?

**Comment by HueLiu** [comment]
![image](https://user-images.githubusercontent.com/19755727/120918906-75be0880-c6e9-11eb-9e7b-f5526fffe561.png)

Log file: [-1622970342569.log](https://github.com/tiddly-gittly/TiddlyGit-Desktop/files/6603901/-1622970342569.log)

**Comment by linonetwo** [comment]
Great, this is clear, will addressed in next release

**Comment by linonetwo** [comment]
Maybe you can try latest prerelease, I didn't encounter this blank page bug

**Comment by linonetwo** [comment]
https://github.com/tiddly-gittly/TiddlyGit-Desktop/releases/tag/v0.4.2-a5 应该修复了吧…

**Comment by HueLiu** [comment]
yes, this CSS issue had been fixed.

But the issue for GitHub sync is still not working.
